[package]
name = "mepoo"
version = "0.1.0"
authors = ["Yuichiro Terada <yuichiro_terada@caddi.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
